import { prisma } from '@/lib/server/db/prisma';
import type { CreateStockItemInput, UpdateStockItemInput } from './stock.validation';

type FindManyOpts = {
  skip?: number;
  take?: number;
  /** Si défini : select léger (autocomplete). Sinon include mouvements count. */
  light?: boolean;
};

export const stockRepository = {
  findMany(where: Record<string, unknown>, opts?: FindManyOpts) {
    if (opts?.light) {
      return prisma.stockItem.findMany({
        where,
        orderBy: [{ category: 'asc' }, { label: 'asc' }],
        skip: opts.skip,
        take: opts.take,
        select: {
          id: true,
          sku: true,
          label: true,
          unit: true,
          quantity: true,
          reservedQty: true,
          unitDisplay: true,
        },
      });
    }
    return prisma.stockItem.findMany({
      where,
      orderBy: [{ category: 'asc' }, { label: 'asc' }],
      skip: opts?.skip,
      take: opts?.take,
      include: { _count: { select: { movements: true } } },
    });
  },

  count(where: Record<string, unknown>) {
    return prisma.stockItem.count({ where });
  },

  findById(id: string) {
    return prisma.stockItem.findUnique({
      where: { id },
      include: {
        movements: { orderBy: { createdAt: 'desc' }, take: 30 },
      },
    });
  },

  create(data: CreateStockItemInput & { sku: string; skuAutoGenerated?: boolean; marginPct?: number | null }) {
    const { autoSku: _a, linkMaterial: _l, skuManual: _m, ...rest } = data;
    return prisma.stockItem.create({ data: rest as Parameters<typeof prisma.stockItem.create>[0]['data'] });
  },

  update(id: string, data: UpdateStockItemInput) {
    return prisma.stockItem.update({
      where: { id },
      data,
      include: {
        movements: { orderBy: { createdAt: 'desc' }, take: 30 },
      },
    });
  },
};
