import type { KpiDefinition } from '@/lib/kpi/registry';

/** COM-007 : acceptés / (émis éligibles hors brouillon) — version 1 approuvée V13. */
export const COMMERCIAL_KPIS: KpiDefinition[] = [
  {
    id: 'COM-007',
    version: 1,
    label: 'Taux de conversion devis',
    description:
      'Numérateur = devis Accepté. Dénominateur = devis émis éligibles (Envoyé + Accepté + Refusé + Expiré), hors Brouillon. Pas CA.',
    ownerDomain: 'commercial',
    ownerRole: 'commercial',
    unit: 'PERCENT',
    grain: 'MONTH',
    canonicalDateField: 'Devis.updatedAt',
    sourceOfTruth: ['Devis'],
    formula: 'count(Accepte) / count(Envoye|Accepte|Refuse|Expire) * 100',
    numerator: 'devis.statut = Accepte',
    denominator: 'devis.statut in (Envoye, Accepte, Refuse, Expire)',
    eligibleStatuses: ['Envoye', 'Accepte', 'Refuse', 'Expire'],
    excludedStatuses: ['Brouillon'],
    sensitivity: 'OPERATIONAL',
    requiredPermission: 'devis:read',
    defaultPeriod: 'month',
    freshnessSlaSeconds: 60,
    comparisonPolicy: 'same_duration_same_scope',
    drilldownRoute: '/devis',
    status: 'ACTIVE',
  },
  {
    id: 'COM-003',
    version: 1,
    label: 'Clients actifs',
    description: 'Clients non archivés. Zéro légitime sans fallback liste locale.',
    ownerDomain: 'crm',
    ownerRole: 'commercial',
    unit: 'COUNT',
    grain: 'CURRENT_STATE',
    canonicalDateField: 'Client.updatedAt',
    sourceOfTruth: ['Client'],
    formula: 'count(archived=false)',
    sensitivity: 'OPERATIONAL',
    requiredPermission: 'clients:read',
    defaultPeriod: 'all',
    freshnessSlaSeconds: 120,
    comparisonPolicy: 'point_in_time',
    drilldownRoute: '/clients',
    status: 'ACTIVE',
  },
  {
    id: 'COM-004',
    version: 1,
    label: 'Devis émis',
    description: 'Devis sortis du brouillon sur la période.',
    ownerDomain: 'commercial',
    ownerRole: 'commercial',
    unit: 'COUNT',
    grain: 'DAY',
    canonicalDateField: 'Devis.createdAt',
    sourceOfTruth: ['Devis'],
    formula: 'count where not Brouillon',
    sensitivity: 'OPERATIONAL',
    requiredPermission: 'devis:read',
    defaultPeriod: 'month',
    freshnessSlaSeconds: 60,
    comparisonPolicy: 'same_duration_same_scope',
    status: 'ACTIVE',
  },
  {
    id: 'COM-005',
    version: 1,
    label: 'Devis acceptés',
    description: 'Valeur acceptée — jamais appelée CA encaissé.',
    ownerDomain: 'commercial',
    ownerRole: 'commercial',
    unit: 'COUNT',
    grain: 'DAY',
    canonicalDateField: 'Devis.acceptedAt',
    sourceOfTruth: ['Devis'],
    formula: 'count(Accepte)',
    sensitivity: 'OPERATIONAL',
    requiredPermission: 'devis:read',
    defaultPeriod: 'month',
    freshnessSlaSeconds: 60,
    comparisonPolicy: 'same_duration_same_scope',
    status: 'ACTIVE',
  },
];
