import type { KpiDefinition } from '@/lib/kpi/registry';

export const EXECUTIVE_KPIS: KpiDefinition[] = [
  {
    id: 'DIR-001',
    version: 1,
    label: 'Encaissements nets',
    description: 'Paiements validés moins remboursements, date ledger.',
    ownerDomain: 'finance',
    ownerRole: 'direction',
    unit: 'MGA',
    grain: 'DAY',
    canonicalDateField: 'Paiement.datePaiement',
    sourceOfTruth: ['Paiement'],
    formula: 'sum(paiements) - sum(remboursements)',
    sensitivity: 'FINANCIAL',
    requiredPermission: 'finance:read',
    defaultPeriod: 'month',
    freshnessSlaSeconds: 60,
    comparisonPolicy: 'same_duration_same_scope',
    drilldownRoute: '/paiements',
    status: 'ACTIVE',
  },
  {
    id: 'DIR-002',
    version: 1,
    label: 'Commandes enregistrées HT',
    description: 'Snapshot HT commandes non annulées, date commande.',
    ownerDomain: 'commercial',
    ownerRole: 'direction',
    unit: 'MGA',
    grain: 'DAY',
    canonicalDateField: 'Commande.createdAt',
    sourceOfTruth: ['Commande'],
    formula: 'sum(commande.total) where not cancelled',
    sensitivity: 'FINANCIAL',
    requiredPermission: 'commandes:read',
    defaultPeriod: 'month',
    freshnessSlaSeconds: 60,
    comparisonPolicy: 'same_duration_same_scope',
    drilldownRoute: '/commandes',
    status: 'ACTIVE',
  },
  {
    id: 'DIR-006',
    version: 1,
    label: 'Marge brute',
    description: 'Revenu reconnu moins coût direct couvert — exige méthode Finance.',
    ownerDomain: 'finance',
    ownerRole: 'direction',
    unit: 'MGA',
    grain: 'MONTH',
    canonicalDateField: 'varies',
    sourceOfTruth: ['Commande', 'StockMovement', 'Charge'],
    formula: 'BLOCKED pending Finance',
    sensitivity: 'FINANCIAL',
    requiredPermission: 'pos:view_margin',
    defaultPeriod: 'month',
    freshnessSlaSeconds: 120,
    comparisonPolicy: 'none_until_approved',
    status: 'BLOCKED',
    blockedReason: 'Arbitrage Finance requis (R07/R08) — couverture coûts incomplète',
  },
  {
    id: 'DIR-007',
    version: 1,
    label: 'Résultat opérationnel',
    description: 'Uniquement si plan de comptes et couverture approuvés.',
    ownerDomain: 'finance',
    ownerRole: 'direction',
    unit: 'MGA',
    grain: 'MONTH',
    canonicalDateField: 'varies',
    sourceOfTruth: ['Paiement', 'Charge'],
    formula: 'BLOCKED',
    sensitivity: 'FINANCIAL',
    requiredPermission: 'pos:view_margin',
    defaultPeriod: 'month',
    freshnessSlaSeconds: 120,
    comparisonPolicy: 'none_until_approved',
    status: 'BLOCKED',
    blockedReason: 'Ne pas nommer bénéfice net une soustraction CA−charges partielle',
  },
  {
    id: 'DIR-008',
    version: 1,
    label: 'Santé entreprise',
    description: 'Score transparent versionné — jamais vert si PARTIAL/ERROR.',
    ownerDomain: 'pilotage',
    ownerRole: 'direction',
    unit: 'SCORE',
    grain: 'CURRENT_STATE',
    canonicalDateField: 'computedAt',
    sourceOfTruth: ['multi'],
    formula: 'weighted domains with quality gate',
    sensitivity: 'OPERATIONAL',
    requiredPermission: 'rapports:read',
    defaultPeriod: 'week',
    freshnessSlaSeconds: 60,
    comparisonPolicy: 'same_version_only',
    status: 'ACTIVE',
  },
];
