import type { KpiDefinition } from '@/lib/kpi/registry';

export const PRODUCTION_KPIS: KpiDefinition[] = [
  {
    id: 'PRO-004',
    version: 1,
    label: 'Commandes en retard',
    description: 'Échéance dépassée + statut non terminal. Distinct de urgent.',
    ownerDomain: 'production',
    ownerRole: 'production',
    unit: 'COUNT',
    grain: 'CURRENT_STATE',
    canonicalDateField: 'Commande.dateLiv',
    sourceOfTruth: ['Commande'],
    formula: 'dateLiv < now AND statut not terminal',
    sensitivity: 'OPERATIONAL',
    requiredPermission: 'production:read',
    defaultPeriod: 'current',
    freshnessSlaSeconds: 30,
    comparisonPolicy: 'point_in_time',
    drilldownRoute: '/commandes',
    status: 'ACTIVE',
  },
  {
    id: 'PRO-005',
    version: 1,
    label: 'Commandes urgentes',
    description: 'Priorité urgente — n’implique pas retard.',
    ownerDomain: 'production',
    ownerRole: 'production',
    unit: 'COUNT',
    grain: 'CURRENT_STATE',
    canonicalDateField: 'Commande.priorite',
    sourceOfTruth: ['Commande'],
    formula: 'priorite = Urgente AND not terminal',
    sensitivity: 'OPERATIONAL',
    requiredPermission: 'production:read',
    defaultPeriod: 'current',
    freshnessSlaSeconds: 30,
    comparisonPolicy: 'point_in_time',
    status: 'ACTIVE',
  },
];

export const STUDIO_KPIS: KpiDefinition[] = [
  {
    id: 'STU-005',
    version: 1,
    label: 'BAT envoyés attente client',
    description: 'Registre canonique Proof — pas la liste filtrée UI.',
    ownerDomain: 'studio',
    ownerRole: 'designer',
    unit: 'COUNT',
    grain: 'CURRENT_STATE',
    canonicalDateField: 'Proof.statut',
    sourceOfTruth: ['Proof'],
    formula: 'statut in registre attente client',
    sensitivity: 'OPERATIONAL',
    requiredPermission: 'bat:read',
    defaultPeriod: 'current',
    freshnessSlaSeconds: 30,
    comparisonPolicy: 'point_in_time',
    status: 'ACTIVE',
  },
];

export const MACHINE_KPIS: KpiDefinition[] = [
  {
    id: 'MAC-006',
    version: 1,
    label: 'Tickets maintenance ouverts',
    description: 'Tickets non clos affectés / globaux selon permission.',
    ownerDomain: 'maintenance',
    ownerRole: 'technicien',
    unit: 'COUNT',
    grain: 'CURRENT_STATE',
    canonicalDateField: 'MaintenanceTicket.statut',
    sourceOfTruth: ['MaintenanceTicket', 'Machine'],
    formula: 'count open tickets',
    sensitivity: 'OPERATIONAL',
    requiredPermission: 'machines:read',
    defaultPeriod: 'current',
    freshnessSlaSeconds: 60,
    comparisonPolicy: 'point_in_time',
    drilldownRoute: '/maintenance/tickets',
    status: 'ACTIVE',
  },
  {
    id: 'MAC-012',
    version: 1,
    label: 'Objectif rendement',
    description: 'Référentiel versionné machine/opération — sinon NOT_APPLICABLE.',
    ownerDomain: 'production',
    ownerRole: 'conducteur',
    unit: 'RATE_FH',
    grain: 'CURRENT_STATE',
    canonicalDateField: 'MachineTarget.effectiveFrom',
    sourceOfTruth: ['MachineTarget'],
    formula: 'lookup target or N/A',
    sensitivity: 'OPERATIONAL',
    requiredPermission: 'production:read',
    defaultPeriod: 'current',
    freshnessSlaSeconds: 300,
    comparisonPolicy: 'same_machine_operation',
    status: 'ACTIVE',
  },
];

export const STOCK_KPIS: KpiDefinition[] = [
  {
    id: 'STK-003',
    version: 1,
    label: 'Ruptures stock',
    description: 'Disponible = physique − réservé ≤ 0.',
    ownerDomain: 'stock',
    ownerRole: 'magasinier',
    unit: 'COUNT',
    grain: 'CURRENT_STATE',
    canonicalDateField: 'StockItem.updatedAt',
    sourceOfTruth: ['StockItem'],
    formula: 'count(quantity - reservedQty <= 0)',
    sensitivity: 'OPERATIONAL',
    requiredPermission: 'stock:read',
    defaultPeriod: 'current',
    freshnessSlaSeconds: 30,
    comparisonPolicy: 'point_in_time',
    drilldownRoute: '/stock',
    status: 'ACTIVE',
  },
  {
    id: 'STK-004',
    version: 1,
    label: 'Sous seuil',
    description: 'Disponible < minQty.',
    ownerDomain: 'stock',
    ownerRole: 'magasinier',
    unit: 'COUNT',
    grain: 'CURRENT_STATE',
    canonicalDateField: 'StockItem.updatedAt',
    sourceOfTruth: ['StockItem'],
    formula: 'available < minQty',
    sensitivity: 'OPERATIONAL',
    requiredPermission: 'stock:read',
    defaultPeriod: 'current',
    freshnessSlaSeconds: 30,
    comparisonPolicy: 'point_in_time',
    status: 'ACTIVE',
  },
];

export const LOGISTICS_KPIS: KpiDefinition[] = [
  {
    id: 'LOG-FIN-COUNT',
    version: 1,
    label: 'Factures impayées (nombre)',
    description: 'Nombre de factures exigibles non soldées — pas un montant.',
    ownerDomain: 'logistique',
    ownerRole: 'livraison',
    unit: 'COUNT',
    grain: 'CURRENT_STATE',
    canonicalDateField: 'Facture.statut',
    sourceOfTruth: ['Facture'],
    formula: 'count unpaid',
    sensitivity: 'OPERATIONAL',
    requiredPermission: 'factures:read',
    defaultPeriod: 'current',
    freshnessSlaSeconds: 60,
    comparisonPolicy: 'point_in_time',
    status: 'ACTIVE',
  },
];

export const FINANCE_KPIS: KpiDefinition[] = [
  {
    id: 'FIN-004',
    version: 1,
    label: 'Encaissements nets',
    description: 'Alias DIR-001 — ledger net remboursements.',
    ownerDomain: 'finance',
    ownerRole: 'caisse',
    unit: 'MGA',
    grain: 'DAY',
    canonicalDateField: 'Paiement.datePaiement',
    sourceOfTruth: ['Paiement'],
    formula: 'paidTotal net',
    sensitivity: 'FINANCIAL',
    requiredPermission: 'finance:read',
    defaultPeriod: 'day',
    freshnessSlaSeconds: 30,
    comparisonPolicy: 'same_duration_same_scope',
    status: 'ACTIVE',
  },
  {
    id: 'FIN-006',
    version: 1,
    label: 'Reste dû clients',
    description: 'Somme max(totalTTC - net payé, 0) factures exigibles.',
    ownerDomain: 'finance',
    ownerRole: 'caisse',
    unit: 'MGA',
    grain: 'CURRENT_STATE',
    canonicalDateField: 'Facture.dateEcheance',
    sourceOfTruth: ['Facture', 'Paiement'],
    formula: 'sum reste',
    sensitivity: 'FINANCIAL',
    requiredPermission: 'finance:read',
    defaultPeriod: 'current',
    freshnessSlaSeconds: 60,
    comparisonPolicy: 'point_in_time',
    status: 'ACTIVE',
  },
];

export const RH_KPIS: KpiDefinition[] = [
  {
    id: 'RH-002',
    version: 1,
    label: 'Présents',
    description: 'Présences du jour — scope personnel/manager/RH.',
    ownerDomain: 'rh',
    ownerRole: 'rh',
    unit: 'COUNT',
    grain: 'DAY',
    canonicalDateField: 'Presence.date',
    sourceOfTruth: ['EmployeePresence'],
    formula: 'count present',
    sensitivity: 'HR_SENSITIVE',
    requiredPermission: 'rh:read',
    defaultPeriod: 'day',
    freshnessSlaSeconds: 120,
    comparisonPolicy: 'point_in_time',
    status: 'ACTIVE',
  },
];

export const COMMUNICATION_KPIS: KpiDefinition[] = [
  {
    id: 'CM-006',
    version: 1,
    label: 'Messages non lus',
    description: 'Par utilisateur/conversation — pas le total TeamMessage.',
    ownerDomain: 'communication',
    ownerRole: 'accueil',
    unit: 'COUNT',
    grain: 'CURRENT_STATE',
    canonicalDateField: 'TalkMessageRead',
    sourceOfTruth: ['TalkMessage', 'TalkMessageRead'],
    formula: 'unread for userId',
    sensitivity: 'OPERATIONAL',
    requiredPermission: 'talk:read',
    defaultPeriod: 'current',
    freshnessSlaSeconds: 15,
    comparisonPolicy: 'point_in_time',
    drilldownRoute: '/messagerie',
    status: 'ACTIVE',
  },
];

export const ADMIN_KPIS: KpiDefinition[] = [
  {
    id: 'ADM-008',
    version: 1,
    label: 'Outbox en attente',
    description: 'Événements OutboxEvent pending/failed.',
    ownerDomain: 'administration',
    ownerRole: 'admin',
    unit: 'COUNT',
    grain: 'CURRENT_STATE',
    canonicalDateField: 'OutboxEvent.createdAt',
    sourceOfTruth: ['OutboxEvent'],
    formula: 'count status in pending,failed',
    sensitivity: 'OPERATIONAL',
    requiredPermission: 'config:view',
    defaultPeriod: 'current',
    freshnessSlaSeconds: 30,
    comparisonPolicy: 'point_in_time',
    drilldownRoute: '/administration/synchronisation',
    status: 'ACTIVE',
  },
];
