import type { RoleProfile } from './types';
import { getHomeRouteForDashboard } from '@/lib/cockpit/dashboard-registry';

/** Profils workspace — inspirés du HTML CRM v29, mappés sur rôles auth existants */
export const ROLE_PROFILES: Record<string, RoleProfile> = {
  director: {
    id: 'director',
    label: 'Direction',
    emoji: '📊',
    color: '#F20A3A',
    homeRoute: '/dashboard',
    authRoles: ['admin', 'manager', 'demo'],
    nav: [
      { type: 'label', text: 'Pilotage' },
      { type: 'link', moduleId: 'cockpit' },
      { type: 'link', moduleId: 'operations' },
      { type: 'link', moduleId: 'rapports' },
      { type: 'link', moduleId: 'rapports_performance' },
      { type: 'link', moduleId: 'historique' },
      { type: 'divider' },
      { type: 'label', text: 'Ventes & CRM' },
      { type: 'link', moduleId: 'clients' },
      { type: 'link', moduleId: 'pos' },
      { type: 'link', moduleId: 'panier' },
      { type: 'link', moduleId: 'devis' },
      { type: 'link', moduleId: 'commandes' },
      { type: 'link', moduleId: 'reclamations' },
      { type: 'link', moduleId: 'ws_commercial' },
      { type: 'divider' },
      { type: 'label', text: 'Production / GPAO' },
      { type: 'link', moduleId: 'production' },
      { type: 'link', moduleId: 'gpao_dossiers' },
      { type: 'link', moduleId: 'planning' },
      { type: 'link', moduleId: 'equipe_taches' },
      { type: 'link', moduleId: 'plan_matiere' },
      { type: 'link', moduleId: 'qualite' },
      { type: 'link', moduleId: 'ws_production' },
      { type: 'link', moduleId: 'ws_faconnage' },
      { type: 'divider' },
      { type: 'label', text: 'Studio & BAT' },
      { type: 'link', moduleId: 'studio_hub' },
      { type: 'link', moduleId: 'bat' },
      { type: 'link', moduleId: 'conception' },
      { type: 'link', moduleId: 'ws_studio' },
      { type: 'divider' },
      { type: 'label', text: 'Machines & Maintenance' },
      { type: 'link', moduleId: 'machines' },
      { type: 'link', moduleId: 'ws_conducteur' },
      { type: 'link', moduleId: 'maintenance_tickets' },
      { type: 'link', moduleId: 'ws_maintenance' },
      { type: 'link', moduleId: 'materiels' },
      { type: 'divider' },
      { type: 'label', text: 'Stock & Achats' },
      { type: 'link', moduleId: 'stock' },
      { type: 'link', moduleId: 'ws_magasin' },
      { type: 'link', moduleId: 'achats' },
      { type: 'link', moduleId: 'fournisseurs' },
      { type: 'divider' },
      { type: 'label', text: 'Logistique' },
      { type: 'link', moduleId: 'livraisons' },
      { type: 'link', moduleId: 'ws_logistique' },
      { type: 'divider' },
      { type: 'label', text: 'Finance' },
      { type: 'link', moduleId: 'factures' },
      { type: 'link', moduleId: 'paiements' },
      { type: 'link', moduleId: 'finance_charges' },
      { type: 'link', moduleId: 'finance_couts' },
      { type: 'link', moduleId: 'finance_fiscalite' },
      { type: 'link', moduleId: 'finance_ventes_directes' },
      { type: 'link', moduleId: 'caisse' },
      { type: 'link', moduleId: 'ws_finance' },
      { type: 'divider' },
      { type: 'label', text: 'RH' },
      { type: 'link', moduleId: 'rh_employes' },
      { type: 'link', moduleId: 'rh_recruitment' },
      { type: 'link', moduleId: 'rh_absences' },
      { type: 'link', moduleId: 'rh_performance' },
      { type: 'link', moduleId: 'rh_paie' },
      { type: 'link', moduleId: 'rh_annonces' },
      { type: 'link', moduleId: 'rh_mon_profil' },
      { type: 'link', moduleId: 'ws_accueil' },
      { type: 'divider' },
      { type: 'label', text: 'Communication' },
      { type: 'link', moduleId: 'equipe_messages' },
      { type: 'link', moduleId: 'equipe_suggestions' },
      { type: 'link', moduleId: 'cm_campagnes' },
      { type: 'link', moduleId: 'cm_relances' },
      { type: 'link', moduleId: 'cm_notifications' },
      { type: 'link', moduleId: 'ws_cm' },
      { type: 'link', moduleId: 'aide' },
      { type: 'divider' },
      { type: 'label', text: 'Administration / Backoffice' },
      { type: 'link', moduleId: 'admin_backoffice' },
      { type: 'link', moduleId: 'admin_catalogue' },
      { type: 'link', moduleId: 'admin_modeles_articles' },
      { type: 'link', moduleId: 'admin_prix_nav' },
      { type: 'link', moduleId: 'admin_variables_nav' },
      { type: 'link', moduleId: 'admin_matieres_nav' },
      { type: 'link', moduleId: 'admin_flux_statuts' },
      { type: 'link', moduleId: 'admin_estimation_temps' },
      { type: 'link', moduleId: 'admin_synchronisation' },
      { type: 'link', moduleId: 'admin_import_export' },
      { type: 'link', moduleId: 'admin_overview' },
      { type: 'link', moduleId: 'admin_permissions' },
      { type: 'link', moduleId: 'admin_annexes' },
      { type: 'link', moduleId: 'admin_ticker' },
      { type: 'link', moduleId: 'parametres' },
      { type: 'divider' },
      { type: 'label', text: 'Mon espace' },
      { type: 'link', moduleId: 'ws_accueil' },
      { type: 'link', moduleId: 'ws_commercial' },
      { type: 'link', moduleId: 'ws_production' },
      { type: 'link', moduleId: 'ws_studio' },
      { type: 'link', moduleId: 'ws_finance' },
      { type: 'link', moduleId: 'ws_cm' },
      { type: 'link', moduleId: 'ws_logistique' },
      { type: 'link', moduleId: 'ws_magasin' },
      { type: 'link', moduleId: 'ws_faconnage' },
      { type: 'link', moduleId: 'ws_conducteur' },
      { type: 'link', moduleId: 'ws_maintenance' },
    ],
  },
  commercial: {
    id: 'commercial',
    label: 'Commercial',
    emoji: '💼',
    color: '#00CFFF',
    homeRoute: '/workspace/commercial',
    authRoles: ['commercial'],
    nav: [
      { type: 'label', text: 'Mon espace' },
      { type: 'link', moduleId: 'ws_commercial' },
      { type: 'link', moduleId: 'rh_mon_profil' },
      { type: 'divider' },
      { type: 'label', text: 'Ventes & CRM' },
      { type: 'link', moduleId: 'clients' },
      { type: 'link', moduleId: 'pos' },
      { type: 'link', moduleId: 'panier' },
      { type: 'link', moduleId: 'devis' },
      { type: 'link', moduleId: 'commandes' },
      { type: 'link', moduleId: 'reclamations' },
      { type: 'divider' },
      { type: 'label', text: 'Suivi' },
      { type: 'link', moduleId: 'factures' },
      { type: 'link', moduleId: 'livraisons' },
      { type: 'link', moduleId: 'cm_relances' },
      { type: 'link', moduleId: 'cm_campagnes' },
      { type: 'link', moduleId: 'equipe_taches' },
      { type: 'link', moduleId: 'rh_absences' },
      { type: 'divider' },
      { type: 'label', text: 'Communication' },
      { type: 'link', moduleId: 'equipe_messages' },
      { type: 'link', moduleId: 'equipe_suggestions' },
    ],
  },
  graphiste: {
    id: 'graphiste',
    label: 'Studio Design',
    emoji: '🎨',
    color: '#FF4A2B',
    homeRoute: '/workspace/studio',
    authRoles: ['designer'],
    nav: [
      { type: 'label', text: 'Mon espace' },
      { type: 'link', moduleId: 'ws_studio' },
      { type: 'link', moduleId: 'rh_mon_profil' },
      { type: 'divider' },
      { type: 'label', text: 'Studio & BAT' },
      { type: 'link', moduleId: 'studio_hub' },
      { type: 'link', moduleId: 'bat' },
      { type: 'link', moduleId: 'conception' },
      { type: 'link', moduleId: 'clients' },
      { type: 'link', moduleId: 'commandes' },
      { type: 'link', moduleId: 'equipe_taches' },
      { type: 'link', moduleId: 'rh_absences' },
      { type: 'divider' },
      { type: 'label', text: 'Communication' },
      { type: 'link', moduleId: 'equipe_messages' },
      { type: 'link', moduleId: 'equipe_suggestions' },
    ],
  },
  operateur: {
    id: 'operateur',
    label: 'Production',
    emoji: '⚙',
    color: '#FF174D',
    homeRoute: '/workspace/production',
    authRoles: ['production'],
    nav: [
      { type: 'label', text: 'Mon espace' },
      { type: 'link', moduleId: 'ws_production' },
      { type: 'link', moduleId: 'ws_magasin' },
      { type: 'link', moduleId: 'rh_mon_profil' },
      { type: 'divider' },
      { type: 'label', text: 'Atelier' },
      { type: 'link', moduleId: 'production' },
      { type: 'link', moduleId: 'gpao_dossiers' },
      { type: 'link', moduleId: 'planning' },
      { type: 'link', moduleId: 'studio_hub' },
      { type: 'link', moduleId: 'commandes' },
      { type: 'link', moduleId: 'bat' },
      { type: 'link', moduleId: 'machines' },
      { type: 'link', moduleId: 'stock' },
      { type: 'link', moduleId: 'equipe_taches' },
      { type: 'link', moduleId: 'rh_absences' },
      { type: 'divider' },
      { type: 'label', text: 'Communication' },
      { type: 'link', moduleId: 'equipe_messages' },
      { type: 'link', moduleId: 'equipe_suggestions' },
    ],
  },
  logistique: {
    id: 'logistique',
    label: 'Logistique',
    emoji: '🚚',
    color: '#FF4A2B',
    homeRoute: '/workspace/logistique',
    authRoles: ['livraison'],
    nav: [
      { type: 'label', text: 'Mon espace' },
      { type: 'link', moduleId: 'ws_logistique' },
      { type: 'link', moduleId: 'rh_mon_profil' },
      { type: 'divider' },
      { type: 'label', text: 'Livraisons' },
      { type: 'link', moduleId: 'livraisons' },
      { type: 'link', moduleId: 'commandes' },
      { type: 'link', moduleId: 'clients' },
      { type: 'link', moduleId: 'paiements' },
      { type: 'link', moduleId: 'equipe_taches' },
      { type: 'link', moduleId: 'rh_absences' },
      { type: 'divider' },
      { type: 'label', text: 'Communication' },
      { type: 'link', moduleId: 'equipe_messages' },
      { type: 'link', moduleId: 'equipe_suggestions' },
    ],
  },
  faconnage: {
    id: 'faconnage',
    label: 'Façonnage',
    emoji: '✂',
    color: '#2e7d32',
    homeRoute: '/workspace/faconnage',
    authRoles: ['faconnage'],
    nav: [
      { type: 'label', text: 'Mon espace' },
      { type: 'link', moduleId: 'ws_faconnage' },
      { type: 'link', moduleId: 'rh_mon_profil' },
      { type: 'divider' },
      { type: 'label', text: 'Atelier' },
      { type: 'link', moduleId: 'machines' },
      { type: 'link', moduleId: 'stock' },
      { type: 'link', moduleId: 'plan_matiere' },
      { type: 'divider' },
      { type: 'label', text: 'Communication' },
      { type: 'link', moduleId: 'equipe_messages' },
      { type: 'link', moduleId: 'equipe_suggestions' },
    ],
  },
  cm_social: {
    id: 'cm_social',
    label: 'Community Manager',
    emoji: '📱',
    color: '#7b1fa2',
    homeRoute: '/workspace/cm',
    authRoles: ['cm'],
    nav: [
      { type: 'label', text: 'Mon espace' },
      { type: 'link', moduleId: 'ws_cm' },
      { type: 'link', moduleId: 'rh_mon_profil' },
      { type: 'divider' },
      { type: 'label', text: 'Commandes & clients' },
      { type: 'link', moduleId: 'commandes' },
      { type: 'link', moduleId: 'clients' },
      { type: 'link', moduleId: 'cm_notifications' },
      { type: 'link', moduleId: 'cm_campagnes' },
      { type: 'link', moduleId: 'cm_relances' },
      { type: 'divider' },
      { type: 'label', text: 'Communication' },
      { type: 'link', moduleId: 'equipe_messages' },
      { type: 'link', moduleId: 'equipe_suggestions' },
    ],
  },
  technicien: {
    id: 'technicien',
    label: 'Technicien',
    emoji: '🔧',
    color: '#37474f',
    homeRoute: '/workspace/maintenance',
    authRoles: ['technicien'],
    nav: [
      { type: 'label', text: 'Mon espace' },
      { type: 'link', moduleId: 'ws_maintenance' },
      { type: 'link', moduleId: 'rh_mon_profil' },
      { type: 'divider' },
      { type: 'label', text: 'Matériels' },
      { type: 'link', moduleId: 'maintenance_tickets' },
      { type: 'link', moduleId: 'materiels' },
      { type: 'link', moduleId: 'machines' },
      { type: 'link', moduleId: 'stock' },
      { type: 'link', moduleId: 'planning' },
      { type: 'divider' },
      { type: 'label', text: 'Communication' },
      { type: 'link', moduleId: 'equipe_messages' },
      { type: 'link', moduleId: 'equipe_suggestions' },
    ],
  },
  finance: {
    id: 'finance',
    label: 'Finance / Caisse',
    emoji: '💰',
    color: '#FFC928',
    homeRoute: '/workspace/finance',
    /** `finance` = profil navigation API ; `caisse` = opérateur caisse */
    authRoles: ['caisse', 'finance'],
    nav: [
      { type: 'label', text: 'Mon espace' },
      { type: 'link', moduleId: 'ws_finance' },
      { type: 'link', moduleId: 'rh_mon_profil' },
      { type: 'link', moduleId: 'caisse' },
      { type: 'divider' },
      { type: 'label', text: 'Finance avancée' },
      { type: 'link', moduleId: 'finance_charges' },
      { type: 'link', moduleId: 'finance_couts' },
      { type: 'link', moduleId: 'finance_fiscalite' },
      { type: 'link', moduleId: 'finance_ventes_directes' },
      { type: 'divider' },
      { type: 'label', text: 'Facturation' },
      { type: 'link', moduleId: 'factures' },
      { type: 'link', moduleId: 'paiements' },
      { type: 'link', moduleId: 'clients' },
      { type: 'link', moduleId: 'devis' },
      { type: 'link', moduleId: 'commandes' },
      { type: 'link', moduleId: 'pos' },
      { type: 'link', moduleId: 'equipe_taches' },
      { type: 'link', moduleId: 'rh_absences' },
      { type: 'divider' },
      { type: 'label', text: 'Communication' },
      { type: 'link', moduleId: 'equipe_messages' },
      { type: 'link', moduleId: 'equipe_suggestions' },
    ],
  },
  accueil: {
    id: 'accueil',
    label: 'Accueil',
    emoji: '🎧',
    color: '#7c3aed',
    homeRoute: '/workspace/accueil',
    authRoles: ['accueil'],
    nav: [
      { type: 'label', text: 'Mon espace' },
      { type: 'link', moduleId: 'ws_accueil' },
      { type: 'link', moduleId: 'rh_mon_profil' },
      { type: 'divider' },
      { type: 'label', text: 'Réception' },
      { type: 'link', moduleId: 'clients' },
      { type: 'link', moduleId: 'commandes' },
      { type: 'link', moduleId: 'devis' },
      { type: 'link', moduleId: 'livraisons' },
      { type: 'divider' },
      { type: 'label', text: 'Communication' },
      { type: 'link', moduleId: 'equipe_messages' },
      { type: 'link', moduleId: 'equipe_suggestions' },
    ],
  },
  conducteur: {
    id: 'conducteur',
    label: 'Conducteur machine',
    emoji: '🖨',
    color: '#1d4ed8',
    homeRoute: '/workspace/conducteur',
    authRoles: ['conducteur'],
    nav: [
      { type: 'label', text: 'Mon espace' },
      { type: 'link', moduleId: 'ws_conducteur' },
      { type: 'link', moduleId: 'rh_mon_profil' },
      { type: 'divider' },
      { type: 'label', text: 'Impression' },
      { type: 'link', moduleId: 'machines' },
      { type: 'link', moduleId: 'planning' },
      { type: 'link', moduleId: 'commandes' },
      { type: 'link', moduleId: 'bat' },
      { type: 'link', moduleId: 'equipe_taches' },
      { type: 'link', moduleId: 'plan_matiere' },
      { type: 'link', moduleId: 'stock' },
      { type: 'divider' },
      { type: 'label', text: 'Communication' },
      { type: 'link', moduleId: 'equipe_messages' },
      { type: 'link', moduleId: 'equipe_suggestions' },
    ],
  },
  lecture: {
    id: 'lecture',
    label: 'Consultation',
    emoji: '👁',
    color: '#9CA3AF',
    homeRoute: '/dashboard',
    authRoles: ['lecture', 'user'],
    nav: [
      { type: 'link', moduleId: 'cockpit' },
      { type: 'link', moduleId: 'clients' },
      { type: 'link', moduleId: 'devis' },
      { type: 'link', moduleId: 'commandes' },
      { type: 'link', moduleId: 'factures' },
      { type: 'link', moduleId: 'production' },
      { type: 'link', moduleId: 'equipe_messages' },
    ],
  },
};

export function resolveRoleProfile(authRole: string): RoleProfile {
  for (const profile of Object.values(ROLE_PROFILES)) {
    if (profile.authRoles.includes(authRole)) return profile;
  }
  return ROLE_PROFILES.lecture;
}

export function getHomeRouteForRole(authRole: string): string {
  return getHomeRouteForDashboard(authRole);
}
