import type { ModuleDatePeriod } from '@/lib/date-filter';
import type { CockpitAlert } from '@/lib/cockpit/build-alerts';

/** Structure stable quand la DB est vide ou indisponible — évite écran rouge. */
export function emptyDashboardStats(period: ModuleDatePeriod = 'month') {
  return {
    period,
    computedAt: new Date().toISOString(),
    emptyDatabase: true,
    kpis: {
      caDay: 0,
      caWeek: 0,
      caMonth: 0,
      caYear: 0,
      caHighlight: 0,
      devisEnAttente: 0,
      devisAcceptes: 0,
      tauxConversion: 0,
      cmdActives: 0,
      enProduction: 0,
      clients: 0,
      cmdRetard: 0,
      facturesImpayees: 0,
      facturesEnRetard: 0,
      montantFacturesEchues: 0,
      livraisonsEnCours: 0,
      paiementsRecusJour: 0,
      cmdUrgentes: 0,
      stockCritique: 0,
      batEnAttente: 0,
      reclamationsOuvertes: 0,
      machinesDown: 0,
      machinesMaintSoon: 0,
      cmdAPlanifier: 0,
      tachesOuvertes: 0,
      tachesBloquees: 0,
      tachesAujourdhui: 0,
      rhActifs: 0,
      rhPresents: 0,
      rhAbsencesPending: 0,
      rhRetards: 0,
      tresorerieMois: 0,
      impayesClients: 0,
      chargesMois: 0,
      dossiersGpao: 0,
      dossiersBloques: 0,
      incidentsGpao: 0,
      caMoinsChargesMois: 0,
      margeApproximativeChargesPct: 0,
      beneficeNet: 0,
      margeGlobale: 0,
      caCommandesMonth: 0,
      margeReelle: 0,
      margeReellePct: 0,
      coutErreurs: 0,
      coutErreursStatus: 'NOT_APPLICABLE',
      caProgressPct: 0,
      plannedWorkloadHours: 0,
      cmCampagnesActives: 0,
    },
    kpiMeta: {
      quality: 'NO_DATA',
      warnings: ['emptyDatabase — zéros non certifiés FRESH'],
      watermark: new Date().toISOString(),
    },
    caChart: [],
    topClients: [],
    topArticles: [],
    machinesStatus: [],
    totalMachines: 0,
    chartsUpdatedAt: new Date().toISOString(),
    chartsPeriodLabel: 'Aucune donnée',
    commandesByStatut: [],
    devisByStatut: [],
    livraisonsByStatut: [],
    machinesChart: [],
    chargesByCategory: [],
    caVsDepenses: [],
    chartsHasEstimatedData: false,
    caByCommercial: [],
    clientsByVille: [],
    caByVille: [],
    caByCanal: [],
    caByCanalDecouverte: [],
    inactiveClients: [],
    impayesParClient: [],
    alertes: [] as CockpitAlert[],
    recentCmds: [],
    recentPaiements: [],
    kpiDrawerHints: {},
    livraisonsPrevues: [],
    recentAudit: [],
    recentAnnonces: [],
    devisEnAttenteList: [],
    commandePeakHours: [],
    topVillesClients: [],
    rhPointage: { presentsToday: 0, retardsToday: 0 },
  };
}
