-- Client CRM channels & fiscal fields (idempotent — Neon / Supabase / Vercel Postgres)
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "canalVente" TEXT;
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "canalDecouverte" TEXT;
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "canalCommande" TEXT;
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "nif" TEXT;
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "statNumber" TEXT;
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "commercialName" TEXT;
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "commercialId" TEXT;
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "categorie" TEXT DEFAULT 'Client';
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "relanceAt" TIMESTAMP(3);
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "charte" TEXT;
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "tags" TEXT;
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "archived" BOOLEAN DEFAULT false;
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "archivedAt" TIMESTAMP(3);
